### ISSUE TITLE
New website layout breaks the script

### ISSUE THREAD

**Issue by kiddikai** [Birnbaum2001/GCComment#13]
Geocaching.com launched a new website layout two weeks ago. Please adapt GCComment to the changes.

**Comment by lukeIam** [comment]
Which problem ocours?
GCC seems to be working for me (with Chrome)

**Comment by kiddikai** [comment]
The Chrome version seems to be working fine indeed. In Firefox, nothing happens at all. No trace of GCC on any page, including my profile and the map.

**Comment by lukeIam** [comment]
I have a test version in my fork (which works with the new layout and the newest FF):
https://github.com/lukeIam/GCComment/blob/newFF/src/gccomment.user.js

I'll make a release these days as I only got positive feedback...

**Comment by kiddikai** [comment]
Thanks!
