### ISSUE TITLE
GC Comment does not show in FF

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#20]
Just recently I switched from Greasemonkey to Tampermonkey in FF (upcoming FF 57 as cause) and suddenly GCComment does not appear in the GC Map. Anyone experiencing this issue as well?

**Comment by f0ssie** [comment]
Yes, I've the same problem with FF ESR 52.5 in combination with Tampermonkey. It seems to be a problem with Tampermonkey, before with Greasemonkey it worked like a charm.

**Comment by lukeIam** [comment]
I'm not longer maintaining this Script and @Birnbaum2001 does neither.

But a as I'm using the script myself (in Chrome) and the new WebExtensions are quite similar to chrome extensions, I made a (hacky) "New-FireFox-Version" for you:
[GCVote_NewFF.zip](https://github.com/Birnbaum2001/GCComment/files/1504047/GCVote_NewFF.zip)

1. Unzip the file to a folder
2. Open FireFox
3. go to about:debugging
4. Enable extension debugging
5. Click Load add-on temporarily
6. Choose the `mainifest.json` from the folder
7. Thats it - in a quick test it was working for me (besides the small maps son the cache pages)
But no guaranties...

**Comment by Cappa-d** [comment]
Works.. however I have switched to FF with Tampermonkey due to the changes with FF 57. will see how it works our in the end.

**Comment by Cappa-d** [comment]
The only thing I am rather puzzled is how to get this to work permanently without reloading it all the time

**Comment by lukeIam** [comment]
I think you have to sign the addon (addons.mozilla.org) then you can
sideload it.

**Comment by ramirezhr** [comment]
Please try this out, Cappa-d
[GCComment.user.zip](https://github.com/Birnbaum2001/GCComment/files/1565426/GCComment.user.zip)

**Comment by Cappa-d** [comment]
manually changed and works perfectly.

**Comment by Cappa-d** [comment]
closed by mistake before it is actually merged --> reopened

**Comment by ramirezhr** [comment]
New Version 91

**Comment by Cappa-d** [comment]
Hi! Machst Du auch noch ne neue FF Version zufällig? :)

**Comment by ramirezhr** [comment]
Ja bestimmt. Die Fehler aus dem Forum schaue ich mir jetzt erstmal an.
