### ISSUE TITLE
Problem with GCComment and GClh installed

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#27]
Hi Ramirez,

ich hab da ein Problem. Bei mir sind unter FF 57.04. mit Tampermonkey v4.5.5660 als Scripte GC-Vote, GClh 0.9 und GCComment 94 installiert.

Wenn ich unter GCComment den Export in die Dropbox starte kommt die Anmeldeseite und er legt auch den GCComment ordner an, aber es öffnet sich dann der Dialog von GClh und es werden die GClh Settings gepeichert.

Irgendeine Idee?

**Comment by ramirezhr** [comment]
Schalte beim ersten Mal GClh aus und wenn du alles fertig hast, wieder ein. Danach läuft alles problemlos. 
Das Fehler ist bekannt und wenn GClh 0.9.1 kommt ist das auch behoben.

**Comment by Cappa-d** [comment]
GClh 0.9.1 ist released damit funktioniert es wieder. Allerdings muss ich auf einem PC noch die Sync mit GClh hinbekommen

**Comment by ramirezhr** [comment]
Ja, GClh hat ja das Token von GCC gespeichert. Möglich wäre, über die Dropbox Webseite die Erlaubnis für beide zurück zu ziehen. So müssen sich beide ein neues Token bei DB holen.

**Comment by Cappa-d** [comment]
All resolved
