### ISSUE TITLE
[Chrome] Cache popup on map not working with gcc

### ISSUE THREAD

**Issue by lukeIam** [Birnbaum2001/GCComment#28]
I can't click on those cache symbols wich has a `link to original` anymore.
Also the cache solution marker is not longer click able.

All other Caches are click able and if I tun off `link to original`  I can also click the cache icon which was not working before.

Using Tampermonkey with Opera (same engine like Chrome).

In the console I get the following error message (one per klick on a not working marker)
```
map.details?i=GCXXXX&jsoncallback=jQuery32107871442649532787_1516201968086&_=1516201968105:1 Uncaught ReferenceError: jQuery32107871442649532787_1516201968086 is not defined
    at map.details?i=GCXXXX&jsoncallback=jQuery32107871442649532787_1516201968086&_=1516201968105:1
(anonymous) @ map.details?i=GCXXXX&jsoncallback=jQuery32107871442649532787_1516201968086&_=1516201968105:1
```

**Comment by Cappa-d** [comment]
Same issue with FF and Tampermonkey

**Comment by Cappa-d** [comment]
Nachtrag: Wenn man den Mystery Mover deaktiviert funktionieren die Links entsprechend wieder.

**Comment by lukeIam** [comment]
> Wenn man den Mystery Mover deaktiviert funktionieren die Links entsprechend wieder.

es reicht wenn man den die Verbindungen zwischen original und neu deaktiviert.

**Comment by Cappa-d** [comment]
> es reicht wenn man den die Verbindungen zwischen original und neu deaktiviert.

In FF leider nicht. Da bleibt es bei den Problemen

**Comment by ramirezhr** [comment]
Hallo ihr zwei,
da ist mir beim testen wohl etwas nicht aufgefallen. Ich nehme den Fehler unter die Lupe und werde schauen das er schnell behoben ist.

**Comment by ramirezhr** [comment]
könnt ihr bitte mal testen? Ein Fix auf die schnelle. Wird dann in Zukunft umgebaut.

https://github.com/ramirezhr/GCComment/raw/dev/src/gccomment.user.js

**Comment by Cappa-d** [comment]
FF geht
Chrome geht

**Comment by lukeIam** [comment]
> könnt ihr bitte mal testen? Ein Fix auf die schnelle. Wird dann in Zukunft umgebaut.
> 
> https://github.com/ramirezhr/GCComment/raw/dev/src/gccomment.user.js

Works! (Opera/Chrome) 🎉

**Comment by lukeIam** [comment]
Thanks for the very fast fix!

**Comment by ramirezhr** [comment]
No problem. Have a nice weekend an some cool caches
