### ISSUE TITLE
New Layout -- F2 Log Button

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#31]
While using the new layout when loging a cache the F2 Log Button is missing. Not sure if the function works at all.

**Comment by Cappa-d** [comment]
Wenn man das alte Layout verwendet ist folgender Button am Ende zu sehen:

![image](https://user-images.githubusercontent.com/10072462/36695643-32c4bda4-1b42-11e8-8dd4-9c78f2a51f91.png)

Im neuen Layout nicht und auch nicht die anderen Checkboxen etc.

**Comment by ramirezhr** [comment]
Die Funktionen gibt es nun. Zwar noch nicht ganz vollständig, aber so gehts schon mal.

Das F2 ist von GC Little Helper auf den alten Log Seiten.
