### ISSUE TITLE
Problem beim Import / Export?

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#33]
Hmmm es scheint Probleme beim Import Export zu geben.

Der Export liefert mir noch eine valide Datei, nur beim Import steht es immer auf 0.

Kann das jemand nachstellen?

Hab es auf zwei Rechner mit Chrome und FF getestet

**Comment by Cappa-d** [comment]
Ich glaube es gab ein tampermonkey update. Gestern ging es noch.
Filter: all --> export to dropbox oder download (geht)

Import weder lokal noch dropbox gibt ein Ergebnis. Die Liste lässt sich laden aber der finale import scheitert. Bin gerade auf tour daher keine screens

**Comment by Cappa-d** [comment]
Ok, anbei einige Details.

Filter für den Export:
![image](https://user-images.githubusercontent.com/10072462/38929323-3194ce14-430c-11e8-9543-f2c9d61f5aa0.png)

Export klappt - bei beiden Varianten. Das File hat im Vergleich zur vorherigen Version ein neue Größe:
-- to add : dropbox details --

Import check gegen Dropbox ok // ebenso lokal ok
![image](https://user-images.githubusercontent.com/10072462/38929527-e1281228-430c-11e8-90c4-b14971492bba.png)

Ausführung des Imports startet auch, aber
![image](https://user-images.githubusercontent.com/10072462/38929563-0884c762-430d-11e8-82ac-a91a45b73249.png)

Unterschiede in den Files:
- Es kamen neue Koords und Stages in einzelnen Caches dazu
- bei einigen vorhandenen hat sich der Status von Solved in Found geändert.

**Comment by Cappa-d** [comment]
ok, Fehler gefunden. Ich hatte in einer Stage Parken & Einstieg eingetragen. Das & wurde im Export nicht sauber umgesetzt und scheitert dann beim Import

**Comment by ramirezhr** [comment]
Das Problem wäre ja von Deiner Seite behoben. Ich hab, nachdem wir geschrieben haben, schon mal einiges im Code geändert und denke mal das bei nächsten Update dieses Problem nicht mehr passieren kann.

**Comment by Cappa-d** [comment]
ok, ich hab es genau lokalisieren können.

Beim Export wird ein & sauber umgewandelt. Beispiel:

<gccode>GC441CH</gccode><name>N 49 &amp; E 008</name><content></content><save>1429091364152</save><state>found</state>

Beim Export einer Stage mit & passiert genau diese Umwandlung nicht....

**Comment by Cappa-d** [comment]
Close war nicht beabsichtigt

**Comment by Cappa-d** [comment]
Sieht soweit gut aus. Lass es mich mal noch bis Montag auf nem anderen Rechner testen. Falls Ok kommentiere ich es hier und schließe den Fall

**Comment by ramirezhr** [comment]
Hallo Cappa,

wie klappt es damit?

**Comment by Cappa-d** [comment]
Problem gelöst -- Import & Export klappt wieder
