### ISSUE TITLE
Dropbox auth seems to fail new layout

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#36]
Hi Ramirez,

ich habe einen Fehler scheinbar gefunden, wenn man einen neuen Browser einrichtet. Zumindest ist dort bei mir das Problem aufgetreten.

Upgrade vom System auf Win 10
Browser: FF ESR 52.9.0

Auth Dropbox brachte mich immer auf das Dashboard zurück, aber ohne erfolgreiche Verbindung.

Umstellung auf altes Layout -- selbe Schritte --> erfolgreiche Verbindung.

Danach wieder auf neues Layout umgestellt und alles geht wie vorher.

Das Problem ist wirklich nur die initiale Verbindung.

Gruß

Cappa-d

**Comment by ramirezhr** [comment]
Fehler behoben mit version 100
