### ISSUE TITLE
Doesn't work with GCTour GPX export

### ISSUE THREAD

**Issue by Cryo99** [Birnbaum2001/GCComment#42]
GCComments appear in GCTour's print output but nothing will make them appear in the GPX, as they always used to. `Allow export of comment data to other scripts (e.g., GC Tour)` is set on the GCComment side. This is about the most useful feature of the combination of these two scripts so I really hope it can be fixed soon.

GCTour 4.18
GCComment 102

Cheers.

**Comment by ramirezhr** [comment]
GCComment works perfect. GCComments appear in GCTour's print output and doesn't appear in GPX. You can Patch the GPX with GCC.
