### ISSUE TITLE
Comments do not load

### ISSUE THREAD

**Issue by daroganadir** [Birnbaum2001/GCComment#5]
Hello,

not sure, if it is a bug but I since a few days I do have a strange behavior: when I go to my profile page of geocaching.com and click on "Show comments" (actually "Zeige meine Kommentare" since I am from germany), nothing happens. With Firefox the browser also hangs for some seconds. No table of comments is shown. Export and import works as expected also making comments in listings.

I do use GC Comment 84 and my browsers are FF30, FF28, Chrome 36. Number of comments is around 700.

Is this a bug or am I doing something wrong.

Thanks in advance!

Nadir.

**Comment by lukeIam** [comment]
Should be fixed...
