### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by daroganadir** [Birnbaum2001/GCComment#6]
Hello,
I found a strange thing with the import, I think. 

I did an export from one browser and imported the file on another. But there not all entries are imported right. 
Example: on browser 1 I exported the file. There is the cache 1 which I solved. I checked the gcc-File: the solution for cache 1 is in there. Then I import the gcc-file into the browser 2. In the textfield, cache 1 is shown. Then I execute the import and in the list of imported solutions cache 1 is shown.  In the table of comments (strangely in one of my Chromes - Version Version 36.0.1985.143 m - I get the comments (see my other opened issue) the cache 1 is listed as solved. But when I open cache 1 or look at it in my bookmark there is no green icon for solved and no corrected coordinates as a comment. If I click on "mark as solved" in the comments (though it is already marked as solved), then I do have the data also in the listing.

Is this the normal behavior or a cache issue or am I doing something wrong ?

Thanks in advance!
Nadir.

**Comment by lukeIam** [comment]
please test https://github.com/lukeIam/GCComment/tree/BringGCCBack

**Comment by lukeIam** [comment]
Should be fixed with the new release.
