### ISSUE TITLE
Strange behaviour -- Chrome and GCComment

### ISSUE THREAD

**Issue by Cappa-d** [Birnbaum2001/GCComment#7]
Hiho!

Just recently upgraded to the new release version. As before the dropbox auth does not work for me at all.. GCLH works perfectly and I do not get it why it does not with GCComment. Auth fails but Folder was created in dropbox.. Export however delivers nothing. Any idea how to solve this?

Tried the hints I found in the geoclub forum...

I understood that MMover does not work in Chrome atm. Any idea if it will in the future?

Not sure if I will switch back from Chrome to FF just because of the GCComment functions.

**Comment by lukeIam** [comment]
> I understood that MMover does not work in Chrome atm. Any idea if it will in the future?

MMover is back with the new release

And a made a new issue for the db problem: #10
