### ISSUE TITLE
404 - GCC_httpsConfigSync 

### ISSUE THREAD

**Issue by MMTLukas** [Birnbaum2001/GCComment#8]
On the big geocaching map under "https://www.geocaching.com/map/default.aspx" the MysteryMover isn't working any longer.

STRG + ALT + J Konsole shows:

http://www.birnbaum2001.com/gccomment/GCComment: 
debug: found URL: https://www.geocaching.com/dummy#GCC_httpsConfigSync
TypeError: can't access dead object

Firebug shows:

"NetworkError: 404 Not Found - https://www.geocaching.com/dummy#GCC_httpsConfigSync"

Firefox: 34.0
GCComment: v85

Any ideas? Thanks!
Best regards,
Lukas

**Comment by lukeIam** [comment]
I'm working on it: 

please test https://github.com/lukeIam/GCComment/tree/BringGCCBack

**Comment by geocachingkdv** [comment]
Is there any news on this yet? I don't know if I am experiencing the same problems. 'old' solved coordinates stored with GCComment display fine on the new map, but it ignores the ones that I have added recently. Is there maybe a maximum number of coordinates that GCComment can store (I admit I have a LOT of solutions stored with it already). I am using version 85, and I followed the link above and it also points to a version 85, so I'm not sure if it is different from what I have already.

**Comment by lukeIam** [comment]
Hi @geocachingkdv,

> I followed the link above and it also points to a version 85, so I'm not sure if it is different from what I have already.

Go to the `dist` there and use the files there.
But anyway: I just made a release 8.6 so the 'main' version should also be up to date.

**Comment by geocachingkdv** [comment]
great, version 86 did the trick for me. Thanks a lot!
